### ISSUE TITLE
Cumulative noise issue on jump

### ISSUE THREAD

**Issue by TheyAreJune** [Vast342/ScienceProject#17]
When jumps are repeated, the noise increases in volume with each one and quickly distorts and overwhelms headphones.

**Comment by Vast342** [comment]
I do not experience this phenomena.

**Comment by Vast342** [comment]
I will attempt to fix this though.

**Comment by TheyAreJune** [comment]
I'll check to see if it's only internally in VS Code or if it also occurs in other browsers. Cannot test it on Chrome though because it does not work on Chrome on my machine

**Comment by TheyAreJune** [comment]
Hardware acceleration on Chrome was disabled. Trying again now

**Comment by TheyAreJune** [comment]
Problem confirmed on both Chrome and Firefox Developer Edition. Cause not known but it may be specific to my machine or some glitchy aspect of DirectX 11 and Nvidia Optimus.

Here is a recording. The recorded audio sounds worse than in person, but it isn't too much different. Likely due to GPU Usage or because it's recording directly from PC and not relative to current volume.

https://user-images.githubusercontent.com/78529777/109201046-540ac800-776f-11eb-8bfb-5e0526ad000a.mp4

**Comment by Vast342** [comment]
I am still working on it!
