### ISSUE TITLE
Nothing On Photos Or Data

### ISSUE THREAD

**Issue by Vast342** [Vast342/ScienceProject#26]
I have the data, but not the photos and would like to insert them in the website. however, I do not know how, as I only know enough to insert the initial information myself.

**Comment by TheyAreJune** [comment]
Add the data and photos and information to the google doc and sheet. It will be added.

**Comment by Vast342** [comment]
I have added the data to the sheet and added the information myself.

**Comment by Vast342** [comment]
I am currently working on adding the images and graph to the NO2 page, and will attempt to add the CO2 information later.

**Comment by Vast342** [comment]
closed with #40
