### ISSUE TITLE
Lack Of Sound, Music, or Background

### ISSUE THREAD

**Issue by Vast342** [Vast342/ScienceProject#32]

**Comment by TheyAreJune** [comment]
It's such a short game that there is no need for music as of right now. We only need two more sounds pretty much and that's for item collection and for storage. If this is still a priority, it needs to be a very low priority

**Comment by Vast342** [comment]
What should be a higher priority?

**Comment by TheyAreJune** [comment]
Getting the images and all statistics and data complete

**Comment by Vast342** [comment]
Okay so now i will search for images, and Could you add the graph from [https://docs.google.com/spreadsheets/d/1ZvYanURDzrmBnQ56n8xomefLKt7Uxun_fjyCV642aAM/edit#gid=0](url)?

**Comment by Vast342** [comment]
I have created the 2 more sounds for picking up the item and placing them, and will close this Issue when it finishes building and i can create a pull request.

**Comment by Vast342** [comment]
closed with #37
